spring.profiles.include=default

#server.address=localhost
server.port=8081
#info.component=Auth Server

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka

feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,metrics,env,beans
management.endpoint.health.show-details=always

spring.main.allow-circular-references=true

# Disable security for testing (optional)
spring.security.users.name=admin
spring.security.users.password=admin

jwt.secret=wPqxQrbYwb1W3vSb4z1M3vIol/259R9pTD39aerY5R0=
spring.main.allow-bean-definition-overriding=true

# Allow Feign clients or other services to call auth endpoints
# CORS (optional, if accessing from browser apps)
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*

# Logging Feign client calls
logging.level.feign.Logger=DEBUG