
server.port=9001

# Eureka Client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://postgres-db:5432/ticketdb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Flyway Configuration
flyway.enabled=true
flyway.locations=classpath:db/migration
flyway.baseline-on-migrate=true
# Ensure Flyway runs the migrations if schema is new

//todo check - delete if not needed authentication
# Auth Service URL for Feign
auth.service.url=http://localhost:8081

# Enable Feign client
spring.main.allow-bean-definition-overriding=true

# Feign Logging
logging.level.feign.Logger=DEBUG

#debug=true