
server.port=8083
# Eureka Client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka

### PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://postgres-db:5432/stockdb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

### Hibernate JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
#spring.flyway.baseline-on-migrate=true
#spring.flyway.validate-on-migrate=true

## Optional logging
#logging.level.org.flywaydb.core=INFO