server.port=8091
spring.application.name=usermgmt

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Flyway Configuration
flyway.enabled=true
flyway.locations=classpath:db/migration
flyway.baseline-on-migrate=true
# Ensure Flyway runs the migrations if schema is new

# Auth Service URL for Feign
auth.service.url=http://localhost:8099

# Enable Feign client
spring.main.allow-bean-definition-overriding=true

# Feign Logging
logging.level.feign.Logger=DEBUG